# Generated by Django 3.1.3 on 2021-01-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, upload_to='img/%Y/%m/%d'),
        ),
    ]
