# Generated by Django 3.1.3 on 2021-01-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img/%Y/%m/%d'),
        ),
    ]
