# Generated by Django 3.1.3 on 2021-01-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20210129_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, upload_to='img/%Y/%m/%d'),
        ),
    ]
